app/models.py
from flask_login import UserMixin
from sqlalchemy import func

from app import db
from app import login_manager


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    time_created = db.Column(db.DateTime, server_default=func.now())

    def __init__(self, username, password):
        self.username = username
        self.password = password


class Exercise(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, default=1)
    type = db.Column(db.Integer)
    quantity = db.Column(db.Integer)
    time_created = db.Column(db.DateTime, server_default=func.now())


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


if __name__ == '__main__':
    db.drop_all()
    db.create_all()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, StringField, PasswordField
from wtforms.fields.html5 import IntegerField
from wtforms.validators import InputRequired, EqualTo


class ExerciseInputForm(FlaskForm):
    name = SelectField("Exercise Name", choices=["Pushups", "Pullups"])
    quantity = IntegerField("How Many?", validators=[InputRequired()], render_kw={"placeholder": "Quantity"})
    submit = SubmitField("Add")


class SignupForm(FlaskForm):
    username = StringField('username', validators=[InputRequired()], render_kw={"placeholder": "Username"})
    password = PasswordField('password',
                             validators=[InputRequired(), EqualTo('confirm', message='Passwords must match')],
                             render_kw={"placeholder": "Password"})
    confirm = PasswordField('Confirm your Password', validators=[InputRequired()],
                            render_kw={"placeholder": "Confirm your password"})
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    username = StringField('username', validators=[InputRequired()], render_kw={"placeholder": "Username"})
    password = PasswordField('password',
                             validators=[InputRequired(), ],
                             render_kw={"placeholder": "Password"})
    submit = SubmitField("Login")

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

app = Flask(__name__)
app.config["SECRET_KEY"] = config.SECRET_KEY
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["SQLALCHEMY_DATABASE_URI"] = config.SQLALCHEMY_DATABASE_URI
login_manager = LoginManager()
login_manager.init_app(app)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app.views import main

app.register_blueprint(main)

app/main.py
from flask import redirect, render_template
from app.forms import ExerciseInputForm
from sqlalchemy import func, cast, Date
import enum
from app.db import db
from app.models import Exercise
from app import app
from datetime import datetime, timedelta


class ExerciseType(enum.Enum):
    Pushups = 1
    Pullups = 2


class TimeFilterType(enum.Enum):
    DAILY = 1
    WEEKLY = 2


@app.route('/', methods=['GET', 'POST'])
def home():
    form = ExerciseInputForm()
    if form.validate_on_submit():
        exercise_type = ExerciseType[form.name.data]
        insert_exercise(exercise_type, form.quantity.data)
        return redirect('/')

    return render_template("index.html", form=form)


@app.route('/statistics')
def statistics():
    return render_template(
        "statistics.html",
        num_pushups_today=get_quantity_by_type(ExerciseType.Pushups),
        num_pullups_today=get_quantity_by_type(ExerciseType.Pullups),
        num_pushups_this_week=get_quantity_by_type(ExerciseType.Pushups, filter_type=TimeFilterType.WEEKLY),
        num_pullups_this_week = get_quantity_by_type(ExerciseType.Pullups, filter_type=TimeFilterType.WEEKLY)
    )


def get_quantity_by_type(exercise_type: ExerciseType, filter_type: TimeFilterType = TimeFilterType.DAILY) -> int:
    query = db.session.query(func.sum(Exercise.quantity)).filter_by(
        user_id=1,
        type=exercise_type.value
    )
    if filter_type == TimeFilterType.WEEKLY:
        monday = datetime.now() - timedelta(days=datetime.now().weekday())
        return query.filter(
            cast(Exercise.time_created, Date) >= monday.date(),
            cast(Exercise.time_created, Date) <= datetime.today().date()
        ).scalar()
    else:
        return query.filter(
            cast(Exercise.time_created, Date) == datetime.today().date()
        ).scalar()


def insert_exercise(exercise_type: ExerciseType, quantity: int) -> None:
    exercise = Exercise(type=exercise_type.value, quantity=quantity)
    db.session.add(exercise)
    db.session.commit()
    return

app/views.py
from flask import redirect, render_template, Blueprint, flash, url_for
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

from app.enums import ExerciseType, TimeFilterType
from app.forms import ExerciseInputForm, SignupForm, LoginForm
from app.models import User
from app.repository import get_quantity_by_type, insert_exercise, insert_user, get_exercises_by_user

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/", methods=["GET", "POST"])
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("main.login"))
    form = ExerciseInputForm()
    if form.validate_on_submit():
        exercise_type = ExerciseType[form.name.data]
        insert_exercise(exercise_type, form.quantity.data, current_user)
        flash("Exercise added!")
        return redirect(url_for("main.home"))

    return render_template("index.html", form=form)


@main.route("/statistics")
def statistics():
    return render_template(
        "statistics.html",
        num_pushups_today=get_quantity_by_type(ExerciseType.Pushups, current_user, TimeFilterType.DAILY) or 0,
        num_pullups_today=get_quantity_by_type(ExerciseType.Pullups, current_user, TimeFilterType.DAILY) or 0,
        num_pushups_this_week=get_quantity_by_type(
            ExerciseType.Pushups,
            current_user,
            filter_type=TimeFilterType.WEEKLY
        ) or 0,
        num_pullups_this_week=get_quantity_by_type(
            ExerciseType.Pullups,
            current_user,
            filter_type=TimeFilterType.WEEKLY
        ) or 0,
    )


@main.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        if User.query.filter_by(username=username).first():
            form.username.errors.append("There already exists a user with this username")
            return render_template('signup.html', form=form)
        password = generate_password_hash(form.password.data)
        user = User(username=username, password=password)
        insert_user(user)
        flash("Sign up successful! Welcome")
        login_user(user)
        return redirect(url_for("main.home"))

    return render_template(
        "signup.html",
        form=form
    )


@main.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            flash("Login Successful")
            return redirect(url_for("main.home"))
        else:
            flash("Login Failed")
            return redirect(url_for("main.login"))

    return render_template("login.html", form=form)


@main.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@main.route("/workout_log")
@login_required
def log():
    exercises_models = get_exercises_by_user(current_user)
    # pdb.set_trace()
    exercises = [
        {
            'type': ExerciseType(exercise.type).name,
            'quantity': exercise.quantity,
            'time_created': exercise.time_created.strftime("%a %b %d %I:%M %p")
        } for exercise in exercises_models
    ]

    return render_template("log.html", exercises=exercises)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
      name="viewport"
    />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="icon" />

    <title>Wayne's Fitness Tracker</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- Custom styles for this template -->
    <link
      href="{{ url_for('static', filename='style.css') }}"
      rel="stylesheet"
    />
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark static-top mb-5">
      <a class="navbar-brand" href="#">Fitness Tracker</a>
      <button
        aria-controls="navbarsExampleDefault"
        aria-expanded="false"
        aria-label="Toggle navigation"
        class="navbar-toggler"
        data-target="#navbarsExampleDefault"
        data-toggle="collapse"
        type="button"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.statistics')}}"
              >Statistics</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.log')}}">Workout Log</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.logout')}}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.signup')}}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.login')}}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main class="container" role="main">{% block content %}{% endblock %}</main>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %} {% for message in messages %}
<div class="alert alert-success" role="alert">{{message}}</div>
{% endfor %} {% endif %} {% endwith %}
<form class="form-inline justify-content-center" method="POST">
  {{ form.csrf_token }}
  <div class="form-group mb-2">{{ form.name(class_="form-control") }}</div>
  <div class="form-group mx-sm-3 mb-2">
    {{ form.quantity(class_="form-control") }}
  </div>
  {{ form.submit(class_="btn btn-primary mb-2") }}
  <button
    type="button"
    id="plusTenButton"
    class="btn btn-outline-secondary ml-5 mb-2"
  >
    +10
  </button>
</form>
<script src="{{ url_for('static', filename='form.js') }}"></script>
{% endblock %}

app/templates/log.html
{% extends "base.html" %} {% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Excercise Type</th>
      <th scope="col">Quantity</th>
      <th scope="col">Time Inputted</th>
    </tr>
  </thead>
  <tbody>
    {% for exercise in exercises %}
    <tr>
      <td>{{exercise['type']}}</td>
      <td>{{exercise['quantity']}}</td>
      <td>{{exercise['time_created']}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%endblock%}

app/templates/login.html
{% extends "base.html" %} {% block content %}
<link href="{{ url_for('static', filename='signup.css') }}" rel="stylesheet" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"
/>
<section class="signup">
  {% with messages = get_flashed_messages() %} {% if messages %} {% for message
  in messages %}
  <div class="alert alert-danger" role="alert">{{message}}</div>
  {% endfor %} {% endif %} {% endwith %}
  <div class="container">
    <div class="signup-content">
      <div class="signup-form">
        <h2 class="form-title">Log in</h2>
        <form method="POST" class="register-form" id="register-form">
          {{ form.csrf_token }}
          <div class="form-group">
            <label for="name"
              ><i class="zmdi zmdi-account material-icons-name"></i
            ></label>
            {{ form.username() }}
          </div>
          <div class="form-group">
            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
            {{ form.password() }}
          </div>
          <div class="form-group form-button">
            {{ form.submit(class_="form-submit") }}
          </div>
        </form>
      </div>
      <div class="signup-image">
        <figure>
          <img
            src="{{ url_for('static', filename='signup-image.jpg') }}"
            alt="sign up image"
          />
        </figure>
        <a
          href="{{url_for('main.signup')}}"
          class="signup-image-link"
          style="text-decoration: underline"
          >Sign me up</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %} {% block content %}
<link href="{{ url_for('static', filename='signup.css') }}" rel="stylesheet" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"
/>
{% if form.errors['password'] %}
<div class="alert alert-danger" role="alert">
  {{form.errors['password'][0]}}
</div>
{% endif %}
<section class="signup">
  <div class="container">
    <div class="signup-content">
      <div class="signup-form">
        <h2 class="form-title">Sign up</h2>
        <form method="POST" class="register-form" id="register-form">
          {{ form.csrf_token }}
          <div class="form-group">
            <label for="name"
              ><i class="zmdi zmdi-account material-icons-name"></i
            ></label>
            {{ form.username() }} {% if form.errors['username'] %}
            <div class="invalid-input">{{form.errors['username'][0]}}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
            {{ form.password() }}
          </div>
          <div class="form-group">
            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
            {{ form.confirm() }}
          </div>
          <div class="form-group form-button">
            {{ form.submit(class_="form-submit") }}
          </div>
        </form>
      </div>
      <div class="signup-image">
        <figure>
          <img
            src="{{ url_for('static', filename='signup-image.jpg') }}"
            alt="sign up image"
          />
        </figure>
        <a
          href="{{url_for('main.login')}}"
          class="signup-image-link"
          style="text-decoration: underline"
          >I am already member</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/statistics.html
{% extends "base.html" %} {% block content %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Today</th>
      <th scope="col">This Week</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Push Ups</th>
      <td>{{num_pushups_today}}</td>
      <td>{{num_pushups_this_week}}</td>
    </tr>
    <tr>
      <th scope="row">Pull Ups</th>
      <td>{{num_pullups_today}}</td>
      <td>{{num_pullups_this_week}}</td>
    </tr>
  </tbody>
</table>
{% endblock %}